name: pawhouse_admin_alpha_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  animated_fab_button_menu: ^0.0.2
  cloud_firestore: ^4.14.0
  fab_circular_menu_plus: ^0.0.2
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.5
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  intl: ^0.19.0
  simple_gradient_text: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/peludosTotal.png
    - assets/images/llegaranHoy.png
    - assets/images/videosDiarios.png
    - assets/images/seVanHoy.png
    - assets/images/circleAvatarPic.png
    - assets/images/pertenencia.png




  
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800